[package]
name = "gcr"
version = "0.4.0"
authors = ["sdttttt <760159537@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13"