use_small_heuristics = "Max"
merge_derives = false
hard_tabs = true
newline_style = "Unix"
wrap_comments = true
use_field_init_shorthand = true
match_arm_leading_pipes = "Always"
struct_field_align_threshold = 30
enum_discrim_align_threshold = 30