name: Linux

on:
    push:
        paths:
            - "**.rs"
            - "**.yaml"
            - "**.yml"
            - "**.toml"
        branches: [master]
    pull_request:
        branches: [master, develop]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest]
                toolchain: [nightly]

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v2

            - name: install rust-toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ matrix.toolchain }}
                  override: true
                  profile: minimal

            - name: Build
              uses: actions-rs/cargo@v1
              with:
                  command: make
                  args: build

            - name: Run cargo bloat
              uses: orf/cargo-bloat-action@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: grc
                  path: ./target/release/grc
