name: MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
        toolchain: [nightly, beta, stable]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        override: true

    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --no-fail-fast

    - name: Upload to codecov.io
      run: bash <(curl -s https://codecov.io/bash)

    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release -v

    - uses: actions/upload-artifact@v2
      with:
        name: grc
        path: target\release\grc