name: Release

on:
  push:
    tags: 
      - 'v**'

env:
  CARGO_TERM_COLOR: always

jobs:
  
  upload:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/cache@v2
      if: ${{ runner.os != 'Windows' }}
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - uses: actions/cache@v2
      if: ${{ runner.os == 'Windows' }}
      with:
        path: |
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Run tests
      run: cargo test --verbose
  
    - name: Build on UNIX
      if: ${{ runner.os != 'Windows' }}
      run: |
        cargo build --release --verbose
        zip --junk-paths gcr.zip ./target/release/gcr
    
    - name: Build on Windows
      if: ${{ runner.os == 'Windows' }}
      run: |
        cargo build --release --verbose
        makecab .\target\release\gcr.exe gcr.zip
  
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: GCR-${{ runner.os }}
        path: gcr.zip
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## GCR ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
         # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: gcr.zip
        asset_name: GCR-${{ runner.os }}.zip
        asset_content_type: application/zip
