name: Rust

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/cache@v2
      if: ${{ runner.os != 'Windows' }}
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
   
    - uses: actions/cache@v2
      if: ${{ runner.os == 'Windows' }}
      with:
        path: |
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Lint Code Base
      if: ${{ runner.os != 'Windows' }}
      uses: github/super-linter@v3
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run tests
      run: cargo test --verbose
  
    - name: Run cargo-tarpaulin
      if: ${{ runner.os == 'Linux' }}
      uses: actions-rs/tarpaulin@v0.1
      with:
        args: '-- --test-threads 1'

    - name: Upload to codecov.io
      if: ${{ runner.os == 'Linux' }}
      uses: codecov/codecov-action@v1.0.2
  
    - name: Build
      run: cargo build --release --verbose
