name: Windows [not contain unit test]

on:
    push:
        branches: [master]
    pull_request:
        branches: [master, develop]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        strategy:
            matrix:
                os: [windows-latest]
                toolchain: [stable]

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v2

            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ matrix.toolchain }}
                  profile: minimal
                  override: true

            - name: Install cargo-make
              uses: actions-rs/cargo@v1
              with:
                  command: install
                  args: --debug cargo-make

            - name: Build
              uses: actions-rs/cargo@v1
              with:
                  command: make
                  args: build

            - uses: actions/upload-artifact@v2
              with:
                  name: grc.exe
                  path: target\release\grc.exe